### ISSUE TITLE
Problema no metodo enviaLote da PanamahTask, o comando toSend.delete(); não apaga o arquivo

### ISSUE THREAD

**Issue by zevedosena-git** [casamagalhaes/panamah-sdk-java#11]
Por estar dentro do bloco 
```
try (Reader r = new BufferedReader(new FileReader(toSend))) { 
.....
toSend.delete(); <-- não faz o delete do arquivo porque o reader está aberto para o arquivo "toSend".
}
```

O BufferedReaderprecisa ser fechado para aplicar o delete.

se colocar fora do bloco o bufferedReader vai estar fechado e o delete vai executar corretamente.
```
try (Reader r = new BufferedReader(new FileReader(toSend))) { 
.....

}
toSend.delete();
```

**Comment by sombriks** [comment]
@zevedosena-git foi liberado o release 2.3.1 do sdk, por favor atualize e veja se resolve o problema dos lotes fechados no windows.

**Comment by zevedosena-git** [comment]
Agora no final do processo está apagando o arquivo da pasta "fechados".
A pasta "enviados" continua com todos arquivos gerados.
Tem alguma rotina que vai limpar a pasta "enviados"?

**Comment by sombriks** [comment]
@zevedosena-git tem sim, na release 2.3.0 foi adicionado um novo parâmetro de configurção, o `maxAgeSent`, com valor padrão de 24 horas.

Você pode recuperar um `PanamahConfig` e, antes de passar ele para o `PanamahStream.init`, mudar o valor dele.
